import type { ThemeConfig } from './types'

export const business: ThemeConfig = {
  id: 'business',
  name: '商务',
  description: '专业稳重的商务风格',
  primaryColor: '#2c3e50',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#2c3e50',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '0 0 12px 0',
    borderBottom: '3px double #2c3e50',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#2c3e50',
    lineHeight: '1.5',
    margin: '28px 0 12px 0',
    padding: '8px 0 8px 14px',
    borderLeft: '4px solid #2c3e50',
    background: '#f5f7fa',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#34495e',
    lineHeight: '1.5',
    margin: '22px 0 10px 0',
    padding: '0 0 6px 0',
    borderBottom: '1px solid #eee',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#34495e',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    letterSpacing: '0.3px',
  },
  blockquote: {
    margin: '0 0 16px 0',
    padding: '14px 18px',
    borderLeft: '4px solid #2c3e50',
    background: '#f5f7fa',
    borderRadius: '0 4px 4px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '1.7',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#1e1e1e',
    color: '#d4d4d4',
    borderRadius: '4px',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#c0392b',
    background: '#f5f7fa',
    padding: '2px 6px',
    borderRadius: '3px',
    border: '1px solid #e8e8e8',
  },
  image: {
    maxWidth: '100%',
    margin: '16px auto',
    display: 'block',
    borderRadius: '4px',
    border: '1px solid #e8e8e8',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#999',
    margin: '8px 0 16px 0',
  },
  link: {
    color: '#2c3e50',
    textDecoration: 'none',
    fontWeight: 'bold',
    borderBottom: '1px solid #2c3e50',
  },
  list: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#2c3e50',
    color: '#fff',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #2c3e50',
    textAlign: 'left',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #ddd',
  },
  hr: {
    border: 'none',
    borderTop: '2px solid #2c3e50',
    margin: '24px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#2c3e50',
  },
  em: {
    fontStyle: 'italic',
    color: '#555',
  },
  footnote: {
    fontSize: '12px',
    color: '#999',
    borderTop: '1px solid #ddd',
    paddingTop: '8px',
    marginTop: '24px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '16px',
    background: '#f5f7fa',
    borderRadius: '4px',
    border: '1px solid #e8e8e8',
  },
  tocItem: {
    fontSize: '14px',
    color: '#2c3e50',
    lineHeight: '2',
  },
}
