import type { ThemeConfig } from './types'

// Claude 品牌风格：温暖的棕橙色调，专业又有亲和力
export const claude: ThemeConfig = {
  id: 'claude',
  name: 'Claude 风格',
  description: 'Anthropic Claude 品牌风格，温暖专业',
  primaryColor: '#D97757',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#D97757',
    lineHeight: '1.6',
    margin: '0 0 20px 0',
    padding: '0 0 14px 0',
    borderBottom: '2px solid #D97757',
    textAlign: 'center',
    letterSpacing: '0.5px',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: '600',
    color: '#2D2B2A',
    lineHeight: '1.5',
    margin: '28px 0 14px 0',
    padding: '8px 0 8px 14px',
    borderLeft: '4px solid #D97757',
    background: '#FDF4EF',
    borderRadius: '0 6px 6px 0',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: '600',
    color: '#2D2B2A',
    lineHeight: '1.5',
    margin: '22px 0 10px 0',
    padding: '4px 0 4px 10px',
    borderLeft: '3px solid #E8A88C',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#4A4543',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#3D3A38',
    lineHeight: '1.9',
    margin: '0 0 16px 0',
    letterSpacing: '0.3px',
  },
  blockquote: {
    margin: '0 0 18px 0',
    padding: '14px 18px',
    borderLeft: '4px solid #D97757',
    background: '#FDF4EF',
    borderRadius: '0 8px 8px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#6B5E57',
    lineHeight: '1.8',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#2D2B2A',
    color: '#E8DDD5',
    borderRadius: '8px',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#D97757',
    background: '#FDF4EF',
    padding: '2px 6px',
    borderRadius: '4px',
    border: '1px solid #F0DDD3',
  },
  image: {
    maxWidth: '100%',
    margin: '18px auto',
    display: 'block',
    borderRadius: '8px',
    boxShadow: '0 2px 12px rgba(217,119,87,0.12)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#9B8E86',
    margin: '8px 0 18px 0',
  },
  link: {
    color: '#D97757',
    textDecoration: 'none',
    borderBottom: '1px solid #E8A88C',
    fontWeight: '500',
  },
  list: {
    fontSize: '15px',
    color: '#3D3A38',
    lineHeight: '1.9',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#D97757',
    color: '#fff',
    fontWeight: '600',
    padding: '10px 14px',
    border: '1px solid #D97757',
    textAlign: 'left',
  },
  tableCell: {
    padding: '9px 14px',
    border: '1px solid #F0DDD3',
    color: '#3D3A38',
  },
  hr: {
    border: 'none',
    height: '2px',
    background: 'linear-gradient(to right, #D97757, #E8A88C, transparent)',
    margin: '28px 0',
  },
  strong: {
    fontWeight: '700',
    color: '#2D2B2A',
  },
  em: {
    fontStyle: 'italic',
    color: '#6B5E57',
  },
  footnote: {
    fontSize: '12px',
    color: '#9B8E86',
    borderTop: '1px solid #F0DDD3',
    paddingTop: '10px',
    marginTop: '28px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '18px',
    background: '#FDF4EF',
    borderRadius: '8px',
    border: '1px solid #F0DDD3',
  },
  tocItem: {
    fontSize: '14px',
    color: '#4A4543',
    lineHeight: '2.2',
  },
}
