import type { ThemeConfig } from './types'

export const dark: ThemeConfig = {
  id: 'dark',
  name: '暗色',
  description: '深邃优雅的暗色主题',
  primaryColor: '#61dafb',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#61dafb',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '0 0 12px 0',
    borderBottom: '2px solid #61dafb',
    textAlign: 'center',
    background: '#1a1a2e',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#e0e0e0',
    lineHeight: '1.5',
    margin: '28px 0 12px 0',
    padding: '8px 12px',
    background: '#16213e',
    borderLeft: '4px solid #61dafb',
    borderRadius: '0 4px 4px 0',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#e0e0e0',
    lineHeight: '1.5',
    margin: '22px 0 10px 0',
    padding: '4px 0 4px 10px',
    borderLeft: '3px solid #61dafb',
    background: '#1a1a2e',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#ccc',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
    background: '#1a1a2e',
  },
  paragraph: {
    fontSize: '15px',
    color: '#d0d0d0',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    letterSpacing: '0.5px',
    background: '#1a1a2e',
  },
  blockquote: {
    margin: '0 0 16px 0',
    padding: '12px 16px',
    borderLeft: '4px solid #61dafb',
    background: '#16213e',
    borderRadius: '0 4px 4px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#aaa',
    lineHeight: '1.7',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#0d1117',
    color: '#c9d1d9',
    borderRadius: '6px',
    border: '1px solid #30363d',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#61dafb',
    background: '#16213e',
    padding: '2px 6px',
    borderRadius: '3px',
  },
  image: {
    maxWidth: '100%',
    margin: '16px auto',
    display: 'block',
    borderRadius: '6px',
    boxShadow: '0 4px 16px rgba(0,0,0,0.3)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#888',
    margin: '8px 0 16px 0',
    background: '#1a1a2e',
  },
  link: {
    color: '#61dafb',
    textDecoration: 'none',
    borderBottom: '1px dashed #61dafb',
  },
  list: {
    fontSize: '15px',
    color: '#d0d0d0',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
    background: '#1a1a2e',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#16213e',
    color: '#61dafb',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #30363d',
    textAlign: 'left',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #30363d',
    background: '#1a1a2e',
    color: '#d0d0d0',
  },
  hr: {
    border: 'none',
    height: '1px',
    background: 'linear-gradient(to right, transparent, #61dafb, transparent)',
    margin: '24px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#fff',
  },
  em: {
    fontStyle: 'italic',
    color: '#aaa',
  },
  footnote: {
    fontSize: '12px',
    color: '#888',
    borderTop: '1px solid #30363d',
    paddingTop: '8px',
    marginTop: '24px',
    background: '#1a1a2e',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '16px',
    background: '#16213e',
    borderRadius: '6px',
    border: '1px solid #30363d',
  },
  tocItem: {
    fontSize: '14px',
    color: '#d0d0d0',
    lineHeight: '2',
  },
}
