import type { ThemeConfig } from './types'

export const elegant: ThemeConfig = {
  id: 'elegant',
  name: '文艺',
  description: '温润雅致的文艺风格',
  primaryColor: '#8B6914',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'normal',
    color: '#8B6914',
    lineHeight: '1.8',
    margin: '0 0 20px 0',
    textAlign: 'center',
    fontFamily: 'serif',
    letterSpacing: '2px',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'normal',
    color: '#8B6914',
    lineHeight: '1.6',
    margin: '28px 0 14px 0',
    textAlign: 'center',
    fontFamily: 'serif',
    letterSpacing: '1px',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#5a4610',
    lineHeight: '1.6',
    margin: '22px 0 10px 0',
    fontFamily: 'serif',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#6b5a1e',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#4a4a4a',
    lineHeight: '2',
    margin: '0 0 18px 0',
    textIndent: '2em',
    letterSpacing: '0.5px',
  },
  blockquote: {
    margin: '0 0 18px 0',
    padding: '16px 20px',
    borderLeft: '3px solid #8B6914',
    background: '#fdf8ec',
    borderRadius: '0 6px 6px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#7a6930',
    lineHeight: '1.8',
    margin: '0',
    fontStyle: 'italic',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 18px 0',
    padding: '16px',
    background: '#faf6ed',
    border: '1px solid #e8dfc0',
    borderRadius: '6px',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#8B6914',
    background: '#fdf8ec',
    padding: '2px 6px',
    borderRadius: '3px',
  },
  image: {
    maxWidth: '100%',
    margin: '18px auto',
    display: 'block',
    borderRadius: '6px',
    boxShadow: '0 2px 8px rgba(139,105,20,0.12)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#a09070',
    margin: '8px 0 18px 0',
    fontStyle: 'italic',
  },
  link: {
    color: '#8B6914',
    textDecoration: 'none',
    borderBottom: '1px solid #8B6914',
  },
  list: {
    fontSize: '15px',
    color: '#4a4a4a',
    lineHeight: '2',
    margin: '0 0 18px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 4px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 18px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#fdf8ec',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #e8dfc0',
    textAlign: 'left',
    color: '#8B6914',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #e8dfc0',
  },
  hr: {
    border: 'none',
    textAlign: 'center',
    margin: '28px 0',
    height: '20px',
    lineHeight: '20px',
    fontSize: '16px',
    color: '#8B6914',
  },
  strong: {
    fontWeight: 'bold',
    color: '#5a4610',
  },
  em: {
    fontStyle: 'italic',
    color: '#7a6930',
  },
  footnote: {
    fontSize: '12px',
    color: '#a09070',
    borderTop: '1px solid #e8dfc0',
    paddingTop: '10px',
    marginTop: '28px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '20px',
    background: '#fdf8ec',
    borderRadius: '6px',
    border: '1px solid #e8dfc0',
  },
  tocItem: {
    fontSize: '14px',
    color: '#5a4610',
    lineHeight: '2.2',
  },
}
