import type { ThemeConfig } from './types'

// 清新自然的绿色风格
export const freshGreen: ThemeConfig = {
  id: 'fresh-green',
  name: '清新绿',
  description: '自然清新的草绿风格',
  primaryColor: '#07c160',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#07c160',
    lineHeight: '1.6',
    margin: '0 0 18px 0',
    padding: '0 0 12px 0',
    borderBottom: '2px solid #07c160',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1a1a1a',
    lineHeight: '1.5',
    margin: '28px 0 12px 0',
    padding: '6px 0 6px 12px',
    borderLeft: '4px solid #07c160',
    background: '#f0faf4',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#1a1a1a',
    lineHeight: '1.5',
    margin: '22px 0 10px 0',
    padding: '4px 8px',
    background: '#f0faf4',
    borderRadius: '4px',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#333',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    letterSpacing: '0.5px',
  },
  blockquote: {
    margin: '0 0 16px 0',
    padding: '12px 16px',
    borderLeft: '4px solid #07c160',
    background: '#f0faf4',
    borderRadius: '0 6px 6px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '1.7',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#f6f8fa',
    borderRadius: '6px',
    border: '1px solid #e1e4e8',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#07c160',
    background: '#f0faf4',
    padding: '2px 6px',
    borderRadius: '3px',
  },
  image: {
    maxWidth: '100%',
    margin: '16px auto',
    display: 'block',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(7,193,96,0.1)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#999',
    margin: '8px 0 16px 0',
  },
  link: {
    color: '#07c160',
    textDecoration: 'none',
    borderBottom: '1px solid #07c160',
  },
  list: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#07c160',
    color: '#fff',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #07c160',
    textAlign: 'left',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #e1e4e8',
  },
  hr: {
    border: 'none',
    height: '2px',
    background: 'linear-gradient(to right, #07c160, #a8e6cf, transparent)',
    margin: '24px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  em: {
    fontStyle: 'italic',
    color: '#555',
  },
  footnote: {
    fontSize: '12px',
    color: '#999',
    borderTop: '1px solid #e1e4e8',
    paddingTop: '8px',
    marginTop: '24px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '16px',
    background: '#f0faf4',
    borderRadius: '6px',
    border: '1px solid #d0ead9',
  },
  tocItem: {
    fontSize: '14px',
    color: '#333',
    lineHeight: '2',
  },
}
