import type { ThemeConfig } from './types'

// 梦幻渐变紫风格
export const gradientPurple: ThemeConfig = {
  id: 'gradient-purple',
  name: '渐变紫',
  description: '梦幻大气的紫色渐变风格',
  primaryColor: '#6c5ce7',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#6c5ce7',
    lineHeight: '1.6',
    margin: '0 0 18px 0',
    padding: '12px 0',
    textAlign: 'center',
    borderBottom: '2px solid #6c5ce7',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#2d3436',
    lineHeight: '1.5',
    margin: '28px 0 12px 0',
    padding: '8px 14px',
    borderLeft: '4px solid #6c5ce7',
    background: 'linear-gradient(to right, #f3f0ff, transparent)',
    borderRadius: '0 6px 6px 0',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#2d3436',
    lineHeight: '1.5',
    margin: '22px 0 10px 0',
    padding: '4px 0 4px 10px',
    borderLeft: '3px solid #a29bfe',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#555',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    letterSpacing: '0.5px',
  },
  blockquote: {
    margin: '0 0 16px 0',
    padding: '14px 18px',
    borderLeft: '4px solid #6c5ce7',
    background: '#f3f0ff',
    borderRadius: '0 8px 8px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '1.7',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#2d2b55',
    color: '#e4e0f0',
    borderRadius: '8px',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#6c5ce7',
    background: '#f3f0ff',
    padding: '2px 6px',
    borderRadius: '4px',
  },
  image: {
    maxWidth: '100%',
    margin: '16px auto',
    display: 'block',
    borderRadius: '8px',
    boxShadow: '0 3px 14px rgba(108,92,231,0.15)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#999',
    margin: '8px 0 16px 0',
  },
  link: {
    color: '#6c5ce7',
    textDecoration: 'none',
    borderBottom: '1px solid #a29bfe',
  },
  list: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#6c5ce7',
    color: '#fff',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #6c5ce7',
    textAlign: 'left',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #e0ddf0',
  },
  hr: {
    border: 'none',
    height: '2px',
    background: 'linear-gradient(to right, #6c5ce7, #a29bfe, transparent)',
    margin: '24px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#2d3436',
  },
  em: {
    fontStyle: 'italic',
    color: '#666',
  },
  footnote: {
    fontSize: '12px',
    color: '#999',
    borderTop: '1px solid #e0ddf0',
    paddingTop: '8px',
    marginTop: '24px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '16px',
    background: '#f3f0ff',
    borderRadius: '8px',
    border: '1px solid #e0ddf0',
  },
  tocItem: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '2',
  },
}
