import type { ThemeConfig } from './types'

// 日本风：和纸留白、朱印红与墨色排版，适合旅行、文化、读书类文章
export const japanClassic: ThemeConfig = {
  id: 'japan-classic',
  name: '日本风',
  description: '和纸留白与朱印红点缀，清雅克制的日本经典风格',
  primaryColor: '#b23a32',
  category: 'classic' as const,
  title: {
    fontSize: '25px',
    fontWeight: '700',
    color: '#b23a32',
    lineHeight: '1.7',
    margin: '0 0 24px 0',
    padding: '12px 0',
    textAlign: 'center',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
    letterSpacing: '2px',
    borderTop: '2px solid #b23a32',
    borderBottom: '2px solid #b23a32',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#2f2926',
    lineHeight: '1.6',
    margin: '30px 0 14px 0',
    padding: '6px 0 6px 14px',
    borderLeft: '5px solid #b23a32',
    borderBottom: '1px solid #eadfce',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
    letterSpacing: '1px',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: '700',
    color: '#3f4f3a',
    lineHeight: '1.6',
    margin: '24px 0 10px 0',
    padding: '4px 0 4px 12px',
    borderLeft: '3px solid #8f9a70',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#4a3a32',
    lineHeight: '1.6',
    margin: '18px 0 8px 0',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
  },
  paragraph: {
    fontSize: '15px',
    color: '#3a332f',
    lineHeight: '2',
    margin: '0 0 17px 0',
    letterSpacing: '0.4px',
    textAlign: 'justify',
  },
  blockquote: {
    margin: '0 0 18px 0',
    padding: '14px 18px',
    borderLeft: '4px solid #b23a32',
    background: '#faf7f0',
    borderRadius: '0 4px 4px 0',
    borderTop: '1px solid #eadfce',
    borderBottom: '1px solid #eadfce',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#6b5b4f',
    lineHeight: '1.9',
    margin: '0',
    fontStyle: 'italic',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.7',
    margin: '0 0 17px 0',
    padding: '16px',
    background: '#2f2926',
    color: '#f6efe3',
    borderRadius: '4px',
    overflowX: 'auto',
    border: '1px solid #4a3a32',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#b23a32',
    background: '#faf7f0',
    padding: '2px 6px',
    borderRadius: '3px',
    border: '1px solid #eadfce',
    fontFamily: 'monospace',
  },
  image: {
    maxWidth: '100%',
    margin: '20px auto',
    display: 'block',
    borderRadius: '4px',
    border: '1px solid #eadfce',
    boxShadow: '0 2px 10px rgba(74,58,50,0.12)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#8a7768',
    margin: '8px 0 20px 0',
    fontStyle: 'italic',
    letterSpacing: '0.4px',
  },
  link: {
    color: '#b23a32',
    textDecoration: 'none',
    borderBottom: '1px solid #b23a32',
    fontWeight: '500',
  },
  list: {
    fontSize: '15px',
    color: '#3a332f',
    lineHeight: '2',
    margin: '0 0 17px 0',
    paddingLeft: '24px',
    letterSpacing: '0.3px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 18px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#b23a32',
    color: '#fffaf3',
    fontWeight: '700',
    padding: '10px 14px',
    border: '1px solid #b23a32',
    textAlign: 'left',
  },
  tableCell: {
    padding: '9px 14px',
    border: '1px solid #eadfce',
    color: '#3a332f',
  },
  hr: {
    border: 'none',
    height: '1px',
    background: 'linear-gradient(to right, transparent, #8f9a70 20%, #b23a32 50%, #8f9a70 80%, transparent)',
    margin: '30px 0',
  },
  strong: {
    fontWeight: '700',
    color: '#b23a32',
  },
  em: {
    fontStyle: 'italic',
    color: '#5f6b4f',
  },
  footnote: {
    fontSize: '12px',
    color: '#8a7768',
    borderTop: '1px solid #eadfce',
    paddingTop: '10px',
    marginTop: '28px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '18px',
    background: '#faf7f0',
    borderRadius: '4px',
    border: '1px solid #eadfce',
    borderLeft: '4px solid #b23a32',
  },
  tocItem: {
    fontSize: '14px',
    color: '#4a3a32',
    lineHeight: '2.2',
    letterSpacing: '0.3px',
  },
}
