import type { ThemeConfig } from './types'

// 信纸风格：米黄色信纸底纹，横线背景，温馨怀旧
export const letterPaper: ThemeConfig = {
  id: 'letter-paper',
  name: '信纸',
  description: '米黄信纸底纹，温馨怀旧的书信风格',
  primaryColor: '#8B4513',
  category: 'background' as const,
  wrapper: {
    background: '#fdf5e6',
    backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 31px, #e6d5b8 31px, #e6d5b8 32px)',
    padding: '24px 20px',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'normal',
    color: '#8B4513',
    lineHeight: '1.8',
    margin: '0 0 20px 0',
    textAlign: 'center',
    fontFamily: '"楷体", "KaiTi", serif',
    letterSpacing: '3px',
    borderBottom: 'none',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'normal',
    color: '#8B4513',
    lineHeight: '1.6',
    margin: '28px 0 14px 0',
    fontFamily: '"楷体", "KaiTi", serif',
    letterSpacing: '1px',
    borderBottom: '1px dashed #c4a882',
    paddingBottom: '6px',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#6b3a0a',
    lineHeight: '1.6',
    margin: '22px 0 10px 0',
    fontFamily: '"楷体", "KaiTi", serif',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#7a5230',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#5a3e28',
    lineHeight: '2',
    margin: '0 0 16px 0',
    textIndent: '2em',
    letterSpacing: '0.5px',
  },
  blockquote: {
    margin: '0 0 18px 0',
    padding: '14px 18px',
    borderLeft: '3px solid #c4a882',
    background: 'rgba(196,168,130,0.12)',
    borderRadius: '0 6px 6px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#7a5e40',
    lineHeight: '1.8',
    margin: '0',
    fontStyle: 'italic',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#f5ead0',
    border: '1px solid #e0d0b0',
    borderRadius: '4px',
    overflowX: 'auto',
    color: '#5a3e28',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#8B4513',
    background: '#f5ead0',
    padding: '2px 6px',
    borderRadius: '3px',
    border: '1px solid #e0d0b0',
  },
  image: {
    maxWidth: '100%',
    margin: '18px auto',
    display: 'block',
    borderRadius: '4px',
    border: '3px solid #e6d5b8',
    boxShadow: '2px 2px 6px rgba(139,69,19,0.1)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#a08060',
    margin: '8px 0 18px 0',
    fontStyle: 'italic',
  },
  link: {
    color: '#8B4513',
    textDecoration: 'none',
    borderBottom: '1px dashed #8B4513',
  },
  list: {
    fontSize: '15px',
    color: '#5a3e28',
    lineHeight: '2',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 4px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: 'rgba(139,69,19,0.12)',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #d4c0a0',
    textAlign: 'left',
    color: '#6b3a0a',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #d4c0a0',
    color: '#5a3e28',
  },
  hr: {
    border: 'none',
    borderTop: '1px dashed #c4a882',
    margin: '28px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#6b3a0a',
  },
  em: {
    fontStyle: 'italic',
    color: '#7a5e40',
  },
  footnote: {
    fontSize: '12px',
    color: '#a08060',
    borderTop: '1px dashed #c4a882',
    paddingTop: '10px',
    marginTop: '28px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '18px',
    background: 'rgba(196,168,130,0.12)',
    borderRadius: '6px',
    border: '1px solid #d4c0a0',
  },
  tocItem: {
    fontSize: '14px',
    color: '#5a3e28',
    lineHeight: '2.2',
  },
}
