import type { ThemeConfig } from './types'

export const minimal: ThemeConfig = {
  id: 'minimal',
  name: '极简',
  description: '干净简约，让内容说话',
  primaryColor: '#333333',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#333333',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '0 0 8px 0',
    borderBottom: '1px solid #eee',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#333333',
    lineHeight: '1.5',
    margin: '24px 0 12px 0',
    padding: '0 0 6px 0',
    borderBottom: '1px solid #f0f0f0',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#333333',
    lineHeight: '1.5',
    margin: '20px 0 10px 0',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#555555',
    lineHeight: '1.5',
    margin: '16px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#555555',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    letterSpacing: '0.5px',
  },
  blockquote: {
    margin: '0 0 16px 0',
    padding: '12px 16px',
    borderLeft: '3px solid #ddd',
    background: '#fafafa',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#888',
    lineHeight: '1.7',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#f6f8fa',
    borderRadius: '4px',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#e83e8c',
    background: '#f6f8fa',
    padding: '2px 6px',
    borderRadius: '3px',
  },
  image: {
    maxWidth: '100%',
    margin: '16px auto',
    display: 'block',
    borderRadius: '4px',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#999',
    margin: '8px 0 16px 0',
  },
  link: {
    color: '#333333',
    textDecoration: 'none',
    borderBottom: '1px solid #333333',
  },
  list: {
    fontSize: '15px',
    color: '#555555',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 4px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#f6f8fa',
    fontWeight: 'bold',
    padding: '8px 12px',
    border: '1px solid #ddd',
    textAlign: 'left',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #ddd',
  },
  hr: {
    border: 'none',
    borderTop: '1px solid #eee',
    margin: '24px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#333',
  },
  em: {
    fontStyle: 'italic',
    color: '#666',
  },
  footnote: {
    fontSize: '12px',
    color: '#999',
    borderTop: '1px solid #eee',
    paddingTop: '8px',
    marginTop: '24px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '16px',
    background: '#fafafa',
    borderRadius: '4px',
  },
  tocItem: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '2',
  },
}
