import type { ThemeConfig } from './types'

// 温柔浪漫的玫瑰粉风格
export const rosePink: ThemeConfig = {
  id: 'rose-pink',
  name: '玫瑰粉',
  description: '温柔浪漫的粉色调',
  primaryColor: '#e84393',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#e84393',
    lineHeight: '1.6',
    margin: '0 0 18px 0',
    padding: '0 0 12px 0',
    borderBottom: '2px solid #e84393',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#2d3436',
    lineHeight: '1.5',
    margin: '28px 0 12px 0',
    padding: '6px 0 6px 12px',
    borderLeft: '4px solid #e84393',
    background: '#fdf0f5',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#2d3436',
    lineHeight: '1.5',
    margin: '22px 0 10px 0',
    padding: '4px 8px',
    background: '#fdf0f5',
    borderRadius: '4px',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#555',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#444',
    lineHeight: '1.9',
    margin: '0 0 16px 0',
    letterSpacing: '0.3px',
  },
  blockquote: {
    margin: '0 0 16px 0',
    padding: '14px 18px',
    borderLeft: '4px solid #e84393',
    background: '#fdf0f5',
    borderRadius: '0 8px 8px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#666',
    lineHeight: '1.7',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#2d3436',
    color: '#dfe6e9',
    borderRadius: '8px',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#e84393',
    background: '#fdf0f5',
    padding: '2px 6px',
    borderRadius: '4px',
  },
  image: {
    maxWidth: '100%',
    margin: '16px auto',
    display: 'block',
    borderRadius: '10px',
    boxShadow: '0 3px 12px rgba(232,67,147,0.12)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#b0a0a8',
    margin: '8px 0 16px 0',
  },
  link: {
    color: '#e84393',
    textDecoration: 'none',
    borderBottom: '1px dashed #e84393',
  },
  list: {
    fontSize: '15px',
    color: '#444',
    lineHeight: '1.9',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#e84393',
    color: '#fff',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #e84393',
    textAlign: 'left',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #f0dde5',
  },
  hr: {
    border: 'none',
    height: '2px',
    background: 'linear-gradient(to right, #e84393, #fd79a8, transparent)',
    margin: '24px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#2d3436',
  },
  em: {
    fontStyle: 'italic',
    color: '#777',
  },
  footnote: {
    fontSize: '12px',
    color: '#b0a0a8',
    borderTop: '1px solid #f0dde5',
    paddingTop: '8px',
    marginTop: '24px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '16px',
    background: '#fdf0f5',
    borderRadius: '8px',
    border: '1px solid #f0dde5',
  },
  tocItem: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '2',
  },
}
