import type { ThemeConfig } from './types'

export const techBlue: ThemeConfig = {
  id: 'tech-blue',
  name: '科技蓝',
  description: '现代感十足的科技风格',
  primaryColor: '#1890ff',
  category: 'classic' as const,
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#1890ff',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '0 0 12px 0',
    borderBottom: '2px solid #1890ff',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1890ff',
    lineHeight: '1.5',
    margin: '28px 0 12px 0',
    padding: '0 0 8px 0',
    borderLeft: '4px solid #1890ff',
    paddingLeft: '12px',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: 'bold',
    color: '#1a1a1a',
    lineHeight: '1.5',
    margin: '22px 0 10px 0',
    padding: '4px 0 4px 10px',
    borderLeft: '3px solid #1890ff',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: '#333',
    lineHeight: '1.5',
    margin: '18px 0 8px 0',
  },
  paragraph: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    letterSpacing: '0.5px',
  },
  blockquote: {
    margin: '0 0 16px 0',
    padding: '12px 16px',
    borderLeft: '4px solid #1890ff',
    background: '#e6f7ff',
    borderRadius: '0 4px 4px 0',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#555',
    lineHeight: '1.7',
    margin: '0',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.6',
    margin: '0 0 16px 0',
    padding: '16px',
    background: '#282c34',
    color: '#abb2bf',
    borderRadius: '6px',
    overflowX: 'auto',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#1890ff',
    background: '#e6f7ff',
    padding: '2px 6px',
    borderRadius: '3px',
  },
  image: {
    maxWidth: '100%',
    margin: '16px auto',
    display: 'block',
    borderRadius: '6px',
    boxShadow: '0 2px 12px rgba(24,144,255,0.15)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#999',
    margin: '8px 0 16px 0',
  },
  link: {
    color: '#1890ff',
    textDecoration: 'none',
    borderBottom: '1px dashed #1890ff',
  },
  list: {
    fontSize: '15px',
    color: '#333',
    lineHeight: '1.8',
    margin: '0 0 16px 0',
    paddingLeft: '24px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 16px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#1890ff',
    color: '#fff',
    fontWeight: 'bold',
    padding: '10px 12px',
    border: '1px solid #1890ff',
    textAlign: 'left',
  },
  tableCell: {
    padding: '8px 12px',
    border: '1px solid #e8e8e8',
  },
  hr: {
    border: 'none',
    height: '2px',
    background: 'linear-gradient(to right, #1890ff, transparent)',
    margin: '24px 0',
  },
  strong: {
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  em: {
    fontStyle: 'italic',
    color: '#555',
  },
  footnote: {
    fontSize: '12px',
    color: '#999',
    borderTop: '1px solid #e8e8e8',
    paddingTop: '8px',
    marginTop: '24px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '16px',
    background: '#e6f7ff',
    borderRadius: '6px',
    borderLeft: '4px solid #1890ff',
  },
  tocItem: {
    fontSize: '14px',
    color: '#333',
    lineHeight: '2',
  },
}
