import type { ThemeConfig } from './types'

// 泰国风：泰式金色、朱红、孔雀绿与靛蓝点缀，保留公众号文章的清晰阅读节奏。
export const thaiClassic: ThemeConfig = {
  id: 'thai-classic',
  name: '泰国风',
  description: '泰式金色主调，朱红、孔雀绿与靛蓝点缀的泰国经典风格',
  primaryColor: '#c9972b',
  category: 'classic' as const,
  title: {
    fontSize: '25px',
    fontWeight: '700',
    color: '#7b241c',
    lineHeight: '1.7',
    margin: '0 0 24px 0',
    padding: '14px 18px',
    textAlign: 'center',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
    letterSpacing: '2px',
    background: 'linear-gradient(180deg, #fff9eb 0%, #fbf1d4 100%)',
    borderTop: '3px double #c9972b',
    borderBottom: '3px double #c9972b',
    boxShadow: 'inset 0 -5px 0 rgba(0,104,97,0.1)',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: '700',
    color: '#7b241c',
    lineHeight: '1.6',
    margin: '30px 0 14px 0',
    padding: '7px 0 7px 15px',
    borderLeft: '5px solid #c9972b',
    borderBottom: '1px solid #ead8a8',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
    letterSpacing: '1px',
  },
  heading3: {
    fontSize: '17px',
    fontWeight: '700',
    color: '#006861',
    lineHeight: '1.6',
    margin: '24px 0 10px 0',
    padding: '4px 0 4px 12px',
    borderLeft: '3px solid #006861',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
  },
  heading4: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#2f3364',
    lineHeight: '1.6',
    margin: '18px 0 8px 0',
    fontFamily: 'Noto Serif SC, Songti SC, serif',
  },
  paragraph: {
    fontSize: '15px',
    color: '#3f3425',
    lineHeight: '2',
    margin: '0 0 17px 0',
    letterSpacing: '0.4px',
    textAlign: 'justify',
  },
  blockquote: {
    margin: '0 0 18px 0',
    padding: '14px 18px',
    borderLeft: '4px solid #c9972b',
    background: '#fff8e8',
    borderRadius: '0 4px 4px 0',
    borderTop: '1px solid #ead8a8',
    borderBottom: '1px solid #ead8a8',
  },
  blockquoteContent: {
    fontSize: '14px',
    color: '#685944',
    lineHeight: '1.9',
    margin: '0',
    fontStyle: 'italic',
  },
  codeBlock: {
    fontSize: '13px',
    lineHeight: '1.7',
    margin: '0 0 17px 0',
    padding: '16px',
    background: '#252a54',
    color: '#fff8e8',
    borderRadius: '4px',
    overflowX: 'auto',
    border: '1px solid #3d4480',
  },
  inlineCode: {
    fontSize: '13px',
    color: '#7b241c',
    background: '#fff8e8',
    padding: '2px 6px',
    borderRadius: '3px',
    border: '1px solid #ead8a8',
    fontFamily: 'monospace',
  },
  image: {
    maxWidth: '100%',
    margin: '20px auto',
    display: 'block',
    borderRadius: '4px',
    border: '1px solid #ead8a8',
    boxShadow: '0 2px 10px rgba(123,36,28,0.13)',
  },
  imageCaption: {
    textAlign: 'center',
    fontSize: '13px',
    color: '#8a7145',
    margin: '8px 0 20px 0',
    fontStyle: 'italic',
    letterSpacing: '0.4px',
  },
  link: {
    color: '#7b241c',
    textDecoration: 'none',
    borderBottom: '1px solid #c9972b',
    fontWeight: '500',
  },
  list: {
    fontSize: '15px',
    color: '#3f3425',
    lineHeight: '2',
    margin: '0 0 17px 0',
    paddingLeft: '24px',
    letterSpacing: '0.3px',
  },
  listItem: {
    margin: '0 0 6px 0',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '0 0 18px 0',
    fontSize: '14px',
  },
  tableHeader: {
    background: '#7b241c',
    color: '#fff8e8',
    fontWeight: '700',
    padding: '10px 14px',
    border: '1px solid #7b241c',
    textAlign: 'left',
  },
  tableCell: {
    padding: '9px 14px',
    border: '1px solid #ead8a8',
    color: '#3f3425',
  },
  hr: {
    border: 'none',
    height: '1px',
    background: 'linear-gradient(to right, transparent, #006861 18%, #c9972b 50%, #7b241c 82%, transparent)',
    margin: '30px 0',
  },
  strong: {
    fontWeight: '700',
    color: '#7b241c',
  },
  em: {
    fontStyle: 'italic',
    color: '#006861',
  },
  footnote: {
    fontSize: '12px',
    color: '#8a7145',
    borderTop: '1px solid #ead8a8',
    paddingTop: '10px',
    marginTop: '28px',
  },
  toc: {
    margin: '0 0 24px 0',
    padding: '18px',
    background: '#fff8e8',
    borderRadius: '4px',
    border: '1px solid #ead8a8',
    borderLeft: '4px solid #c9972b',
  },
  tocItem: {
    fontSize: '14px',
    color: '#2f3364',
    lineHeight: '2.2',
    letterSpacing: '0.3px',
  },
}
